export interface AlgorithmSourceAudit {
  chapter: number;
  sourceTitle: string;
  bookAnchor: string;
  sourceCue: string;
  catalogIds: string[];
  easy: string;
  technical: string;
}

export const algorithmSourceAudits: AlgorithmSourceAudit[] = [
  { chapter: 1, sourceTitle: "Tic-tac-toe temporal-difference learner", bookAnchor: "Section 1.5", sourceCue: "Introductory self-play example", catalogIds: ["ch1-2"], easy: "The first worked learning loop: update earlier board positions from later board positions.", technical: "Covers the value-table TD update, exploratory action choice, terminal-value anchors, and self-play improvement logic." },
  { chapter: 2, sourceTitle: "Sample-average action-value method", bookAnchor: "Sections 2.2-2.4", sourceCue: "Incremental sample-average bandit update", catalogIds: ["ch2-1"], easy: "Average the rewards seen from each arm and prefer the arm with the best estimate.", technical: "Maps to Q_{n+1}=Q_n+(1/n)(R_n-Q_n), action counts, stationarity assumptions, and greedy/epsilon-greedy use." },
  { chapter: 2, sourceTitle: "Constant-step-size tracking", bookAnchor: "Section 2.5", sourceCue: "Nonstationary bandit update", catalogIds: ["ch2-2"], easy: "Forget old rewards gradually so a drifting arm can be tracked.", technical: "Covers exponential recency weighting, alpha as tracking rate, and bias from initialization." },
  { chapter: 2, sourceTitle: "epsilon-greedy action selection", bookAnchor: "Sections 2.2-2.3", sourceCue: "Exploration/exploitation baseline", catalogIds: ["ch2-3"], easy: "Usually exploit, sometimes try a random arm.", technical: "Covers action probabilities, tie handling, coverage, and regret/exploration tradeoffs." },
  { chapter: 2, sourceTitle: "Optimistic initial values", bookAnchor: "Section 2.6", sourceCue: "Exploration by initialization", catalogIds: ["ch2-4"], easy: "Start every arm with an unrealistically hopeful score so untried arms are attractive.", technical: "Covers transient optimism, dependence on stationarity, and why optimism decays through updates." },
  { chapter: 2, sourceTitle: "Upper-confidence-bound action selection", bookAnchor: "Section 2.7", sourceCue: "UCB action rule", catalogIds: ["ch2-5"], easy: "Choose using both estimated reward and uncertainty bonus.", technical: "Covers the UCB bonus, count dependence, zero-count handling, and reward-scale tuning." },
  { chapter: 2, sourceTitle: "Gradient bandit algorithm", bookAnchor: "Section 2.8", sourceCue: "Preference-gradient bandit", catalogIds: ["ch2-6"], easy: "Learn preferences for actions rather than their reward averages.", technical: "Covers softmax preferences, average-reward baseline, stochastic-gradient ascent interpretation, and preference updates." },

  { chapter: 3, sourceTitle: "Bellman expectation backup", bookAnchor: "Sections 3.5-3.6", sourceCue: "Policy-value recursion", catalogIds: ["ch3-2"], easy: "Value equals reward now plus value later, averaged under the policy.", technical: "Covers p(s',r|s,a), v_pi/q_pi recursions, and expectation over policy and dynamics." },
  { chapter: 3, sourceTitle: "Bellman optimality backup", bookAnchor: "Section 3.6", sourceCue: "Optimal-value recursion", catalogIds: ["ch3-3"], easy: "Pick the action whose one-step lookahead has the best long-run value.", technical: "Covers max backups, q_* and v_* definitions, and the fixed-point target used later by DP and Q-learning." },

  { chapter: 4, sourceTitle: "Iterative policy evaluation", bookAnchor: "Section 4.1 boxed algorithm", sourceCue: "Algorithm parameter theta", catalogIds: ["ch4-1"], easy: "Repeatedly rescore states for a fixed policy until the scores barely change.", technical: "Covers synchronous/in-place Bellman expectation sweeps, terminal values, delta stopping, and model dependence." },
  { chapter: 4, sourceTitle: "Policy improvement", bookAnchor: "Section 4.2", sourceCue: "Greedy improvement theorem", catalogIds: ["ch4-2"], easy: "After scoring the policy, switch each state to the action that looks best.", technical: "Covers one-step lookahead, q_pi from v_pi, greedy action selection, and monotonic policy improvement." },
  { chapter: 4, sourceTitle: "Policy iteration", bookAnchor: "Section 4.3 boxed algorithm", sourceCue: "Evaluation/improvement loop", catalogIds: ["ch4-3"], easy: "Alternate between judging a policy and improving it until it stops changing.", technical: "Covers stable-policy termination, exact versus truncated evaluation, and generalized policy iteration." },
  { chapter: 4, sourceTitle: "Value iteration", bookAnchor: "Section 4.4 boxed algorithm", sourceCue: "Optimality backup sweep", catalogIds: ["ch4-4"], easy: "Skip full evaluation and repeatedly apply the best-action backup.", technical: "Covers Bellman optimality sweeps, theta stopping, greedy policy extraction, and relation to truncated policy iteration." },
  { chapter: 4, sourceTitle: "Asynchronous dynamic programming", bookAnchor: "Section 4.5", sourceCue: "Non-sweep DP", catalogIds: ["ch4-5"], easy: "Update useful states whenever you get to them instead of sweeping every state each time.", technical: "Covers in-place updates, state-selection schedules, convergence coverage conditions, and real-time interleaving." },

  { chapter: 5, sourceTitle: "First-visit MC prediction", bookAnchor: "Section 5.1 boxed algorithm", sourceCue: "Episode-return averaging", catalogIds: ["ch5-1"], easy: "After an episode, average the first return seen after each state.", technical: "Covers first-visit filtering, return accumulation backward through an episode, and unbiased sample-return estimation." },
  { chapter: 5, sourceTitle: "Every-visit MC prediction", bookAnchor: "Section 5.1 variant", sourceCue: "Every occurrence update", catalogIds: ["ch5-2"], easy: "Update from every occurrence of a state in the episode.", technical: "Covers every-visit return samples, dependency between returns, and later compatibility with approximation/traces." },
  { chapter: 5, sourceTitle: "Monte Carlo ES", bookAnchor: "Section 5.3 boxed algorithm", sourceCue: "Exploring-starts control", catalogIds: ["ch5-3"], easy: "Force starts from all state-action pairs so greedy improvement can see every action.", technical: "Covers exploring-start coverage, episode returns for q estimates, and greedy policy improvement." },
  { chapter: 5, sourceTitle: "On-policy first-visit MC control", bookAnchor: "Section 5.4 boxed algorithm", sourceCue: "epsilon-soft policy control", catalogIds: ["ch5-4"], easy: "Keep exploring with an epsilon-soft policy while improving toward greedy actions.", technical: "Covers epsilon-soft policy updates, first-visit action-value returns, and generalized policy iteration without exploring starts." },
  { chapter: 5, sourceTitle: "Off-policy MC prediction", bookAnchor: "Section 5.6 boxed algorithm", sourceCue: "Weighted importance-sampling evaluator", catalogIds: ["ch5-5", "ch5-6", "ch5-7", "ch5-9"], easy: "Learn about one policy from episodes produced by another policy by correcting probability mismatch.", technical: "Covers ordinary and weighted importance sampling, cumulative weights C(s,a), ratio products, and per-decision variants." },
  { chapter: 5, sourceTitle: "Off-policy MC control", bookAnchor: "Section 5.7 boxed algorithm", sourceCue: "Greedy target with behavior coverage", catalogIds: ["ch5-8"], easy: "Use exploratory behavior but improve a greedy target policy from corrected returns.", technical: "Covers target/behavior separation, weighted returns, break conditions when behavior action is inconsistent with greedy target, and coverage assumptions." },

  { chapter: 6, sourceTitle: "Tabular TD(0)", bookAnchor: "Section 6.1 boxed algorithm", sourceCue: "One-step TD prediction", catalogIds: ["ch6-1"], easy: "Update a state immediately from reward plus the next state's current score.", technical: "Covers TD error, bootstrapping, terminal handling, and incremental prediction under a fixed policy." },
  { chapter: 6, sourceTitle: "Sarsa", bookAnchor: "Section 6.4 boxed algorithm", sourceCue: "On-policy TD control", catalogIds: ["ch6-2"], easy: "Learn the value of the action actually taken next, including exploration.", technical: "Covers the S,A,R,S',A' target, on-policy control, epsilon-greedy behavior, and cliff-walking safety behavior." },
  { chapter: 6, sourceTitle: "Q-learning", bookAnchor: "Section 6.5 boxed algorithm", sourceCue: "Off-policy TD control", catalogIds: ["ch6-3"], easy: "Learn the greedy target even while behaving exploratorily.", technical: "Covers max-action bootstrap, behavior/target separation, convergence coverage, and maximization bias context." },
  { chapter: 6, sourceTitle: "Expected Sarsa", bookAnchor: "Section 6.6", sourceCue: "Expected next-action target", catalogIds: ["ch6-4"], easy: "Average over possible next actions instead of sampling one.", technical: "Covers expectation under the policy, variance reduction, on/off-policy variants, and computational cost." },
  { chapter: 6, sourceTitle: "Double Q-learning", bookAnchor: "Section 6.7 boxed algorithm", sourceCue: "Double estimator control", catalogIds: ["ch6-5"], easy: "Use two value tables so one chooses the action and the other judges it.", technical: "Covers estimator decoupling, random table updates, overestimation-bias reduction, and target construction." },
  { chapter: 6, sourceTitle: "Afterstate TD control", bookAnchor: "Section 6.8", sourceCue: "Afterstate values", catalogIds: ["ch6-6"], easy: "Score the board position after your move instead of every action separately.", technical: "Covers state aggregation after deterministic action effects, update reuse, and games such as tic-tac-toe/backgammon." },

  { chapter: 7, sourceTitle: "n-step TD", bookAnchor: "Section 7.1 boxed algorithm", sourceCue: "n-step prediction", catalogIds: ["ch7-1"], easy: "Wait n rewards, then update from the partial return plus a bootstrap.", technical: "Covers n-step returns, delayed tau updates, terminal truncation, and the TD/MC continuum." },
  { chapter: 7, sourceTitle: "n-step Sarsa", bookAnchor: "Section 7.2 boxed algorithm", sourceCue: "n-step action-value control", catalogIds: ["ch7-2"], easy: "Use n-step returns for the state-action pairs in a control trajectory.", technical: "Covers rolling buffers, n-step action-value returns, epsilon-greedy policy improvement, and terminal cases." },
  { chapter: 7, sourceTitle: "Off-policy n-step Sarsa", bookAnchor: "Section 7.3 boxed algorithm", sourceCue: "Importance-sampled n-step control", catalogIds: ["ch7-3", "ch7-4"], easy: "Reuse trajectories from another policy by multiplying corrections across the backup window.", technical: "Covers trajectory probability ratios, per-decision control variates, variance hazards, and target/behavior separation." },
  { chapter: 7, sourceTitle: "n-step tree backup", bookAnchor: "Section 7.5 boxed algorithm", sourceCue: "Tree-backup expectation", catalogIds: ["ch7-5"], easy: "Back up through a tree of expected actions without sampling all of them.", technical: "Covers expected branches under the target policy, no importance-ratio product, and recursive n-step tree targets." },
  { chapter: 7, sourceTitle: "n-step Q(sigma)", bookAnchor: "Section 7.6 boxed algorithm", sourceCue: "Sample/expectation unifier", catalogIds: ["ch7-6"], easy: "Use sigma as a dial between Sarsa-style sampling and tree-backup expectation.", technical: "Covers sigma-weighted backups, unification of Sarsa and tree backup, and per-step mixture choices." },

  { chapter: 8, sourceTitle: "Random-sample one-step tabular Q-planning", bookAnchor: "Section 8.1", sourceCue: "Q-planning procedure", catalogIds: ["ch8-10"], easy: "Practice Q-learning updates on simulated transitions.", technical: "Covers the model-generated one-step Q-learning backup and planning distribution choice." },
  { chapter: 8, sourceTitle: "Dyna-Q", bookAnchor: "Section 8.2 boxed algorithm", sourceCue: "Direct RL plus model planning", catalogIds: ["ch8-1"], easy: "Learn from the real world, remember a model, then rehearse from the model.", technical: "Covers integrated direct learning, model learning, random planning backups, and shared Q-update semantics." },
  { chapter: 8, sourceTitle: "Dyna-Q+", bookAnchor: "Section 8.3", sourceCue: "Exploration bonus in planning", catalogIds: ["ch8-2"], easy: "Prefer actions not tried recently so the model checks for changes.", technical: "Covers time-since-tried bonuses, changing-maze adaptation, and model-based exploration." },
  { chapter: 8, sourceTitle: "Prioritized sweeping", bookAnchor: "Section 8.4", sourceCue: "Priority-queue planning", catalogIds: ["ch8-3"], easy: "Spend planning updates where the value error is largest.", technical: "Covers predecessor models, priority thresholds, queue updates, and backward propagation of surprising changes." },
  { chapter: 8, sourceTitle: "Expected versus sample model updates", bookAnchor: "Section 8.5", sourceCue: "Planning backup comparison", catalogIds: ["ch8-4"], easy: "Choose between averaging all possible outcomes and sampling a few.", technical: "Covers computational cost, branching factor, variance, and expected model backups." },
  { chapter: 8, sourceTitle: "Trajectory sampling", bookAnchor: "Section 8.6", sourceCue: "State distribution for planning", catalogIds: ["ch8-5"], easy: "Plan along states the policy is likely to visit.", technical: "Covers on-policy planning distributions versus uniform sweeps and their impact on useful backups." },
  { chapter: 8, sourceTitle: "Real-time dynamic programming", bookAnchor: "Section 8.7", sourceCue: "Focused value iteration", catalogIds: ["ch8-6"], easy: "Do DP backups only on states reached by simulated or real trajectories.", technical: "Covers asynchronous value iteration focused by start-state reachability and greedy trajectories." },
  { chapter: 8, sourceTitle: "Rollout algorithms", bookAnchor: "Section 8.10", sourceCue: "Decision-time Monte Carlo planning", catalogIds: ["ch8-8"], easy: "Try each action in simulation, then follow a rollout policy to estimate consequences.", technical: "Covers policy-improvement view of rollouts, action comparison from simulated returns, and decision-time planning." },
  { chapter: 8, sourceTitle: "Monte Carlo tree search", bookAnchor: "Section 8.11", sourceCue: "Search tree with rollouts", catalogIds: ["ch8-9"], easy: "Grow a search tree toward promising actions while using rollouts beyond the tree.", technical: "Covers selection, expansion, simulation, backup, visit counts, and UCT-style exploration." },

  { chapter: 9, sourceTitle: "Gradient Monte Carlo", bookAnchor: "Section 9.3 boxed algorithm", sourceCue: "Gradient prediction from returns", catalogIds: ["ch9-1"], easy: "Move weights to make predicted values closer to observed returns.", technical: "Covers differentiable value approximation, stochastic-gradient regression target G_t, and episodic updates." },
  { chapter: 9, sourceTitle: "Semi-gradient TD(0)", bookAnchor: "Section 9.4 boxed algorithm", sourceCue: "Bootstrapped approximate prediction", catalogIds: ["ch9-2"], easy: "Use TD targets with shared function-approximation weights.", technical: "Covers semi-gradient treatment of the bootstrap target, linear stability, and projected fixed points." },
  { chapter: 9, sourceTitle: "n-step semi-gradient TD", bookAnchor: "Section 9.5 boxed algorithm", sourceCue: "Approximate n-step prediction", catalogIds: ["ch9-3"], easy: "Use longer partial returns to train a value approximator.", technical: "Covers n-step targets with features, delayed updates, and the MC/TD approximation continuum." },
  { chapter: 9, sourceTitle: "Least-squares TD", bookAnchor: "Section 9.8 boxed algorithm", sourceCue: "LSTD linear solver", catalogIds: ["ch9-6"], easy: "Solve for linear value weights from accumulated equations instead of small TD steps.", technical: "Covers A,b accumulation, O(d^2) storage, epsilon regularization, and batch/incremental least-squares prediction." },

  { chapter: 10, sourceTitle: "Episodic semi-gradient Sarsa", bookAnchor: "Section 10.1 boxed algorithm", sourceCue: "Approximate episodic control", catalogIds: ["ch10-1"], easy: "Use Sarsa control when Q values come from features and weights.", technical: "Covers action-value feature vectors, semi-gradient TD control, epsilon-greedy action selection, and terminal targets." },
  { chapter: 10, sourceTitle: "Episodic semi-gradient n-step Sarsa", bookAnchor: "Section 10.2 boxed algorithm", sourceCue: "Approximate n-step control", catalogIds: ["ch10-2"], easy: "Train the action-value approximator from n-step control returns.", technical: "Covers n-step action-value buffers, feature-gradient updates, and bootstrapped episodic control." },
  { chapter: 10, sourceTitle: "Average reward estimation", bookAnchor: "Section 10.3", sourceCue: "Continuing-task objective", catalogIds: ["ch10-3"], easy: "Track the long-run reward rate instead of discounting the future.", technical: "Covers differential returns, average reward baseline R_bar, and continuing-control objective changes." },
  { chapter: 10, sourceTitle: "Differential semi-gradient Sarsa", bookAnchor: "Section 10.4 boxed algorithm", sourceCue: "One-step continuing control", catalogIds: ["ch10-4"], easy: "Subtract the average reward in every TD target for continuing tasks.", technical: "Covers differential TD error, reward-rate updates, and semi-gradient control without episode termination." },
  { chapter: 10, sourceTitle: "Differential semi-gradient n-step Sarsa", bookAnchor: "Section 10.5 boxed algorithm", sourceCue: "n-step continuing control", catalogIds: ["ch10-5"], easy: "Use multiple average-adjusted rewards before bootstrapping.", technical: "Covers n-step differential returns, continuing buffers, and reward-rate plus weight updates." },

  { chapter: 11, sourceTitle: "Off-policy semi-gradient TD", bookAnchor: "Sections 11.1-11.3", sourceCue: "Deadly-triad counterexamples", catalogIds: ["ch11-1"], easy: "The simple off-policy bootstrap update can diverge with shared weights.", technical: "Covers why function approximation, bootstrapping, and off-policy sampling break the tabular TD intuition." },
  { chapter: 11, sourceTitle: "Bellman-error gradient descent", bookAnchor: "Section 11.6", sourceCue: "Bellman error objective", catalogIds: ["ch11-4"], easy: "Try to directly minimize Bellman error, but notice the double-sampling problem.", technical: "Covers residual-gradient logic, objective issues, and why the gradient is not the ordinary TD update." },
  { chapter: 11, sourceTitle: "Gradient-TD / TDC", bookAnchor: "Section 11.7", sourceCue: "Stable off-policy objective", catalogIds: ["ch11-2"], easy: "Add a second set of weights so the off-policy update follows a real objective.", technical: "Covers MSPBE-style objectives, primary and secondary weights, and TDC/GTD stability rationale." },
  { chapter: 11, sourceTitle: "Emphatic TD", bookAnchor: "Section 11.8", sourceCue: "Emphasis weighting", catalogIds: ["ch11-3"], easy: "Weight updates by how much states matter under the target policy, not only how often behavior visits them.", technical: "Covers follow-on traces, interest, emphasis, and off-policy stability via state weighting." },

  { chapter: 12, sourceTitle: "Offline lambda-return", bookAnchor: "Section 12.1", sourceCue: "Forward-view lambda target", catalogIds: ["ch12-1"], easy: "Average all n-step returns with lambda weights after the episode.", technical: "Covers lambda-return mixture, forward-view target, and TD/MC interpolation." },
  { chapter: 12, sourceTitle: "TD(lambda)", bookAnchor: "Section 12.2 boxed algorithm", sourceCue: "Backward-view prediction traces", catalogIds: ["ch12-2"], easy: "Carry an eligibility trace so one TD error updates many recent states.", technical: "Covers accumulating/replacing traces, backward-view equivalence, and trace decay gamma lambda." },
  { chapter: 12, sourceTitle: "Online lambda-return", bookAnchor: "Section 12.4", sourceCue: "Redoing updates", catalogIds: ["ch12-9"], easy: "Update online while repeatedly correcting earlier interim lambda targets.", technical: "Covers online forward-view revisions, interim lambda-returns, and computational tradeoffs." },
  { chapter: 12, sourceTitle: "True online TD(lambda)", bookAnchor: "Section 12.5 boxed algorithm", sourceCue: "Dutch trace prediction", catalogIds: ["ch12-3"], easy: "Correct TD(lambda) so online updates match the forward-view target more exactly.", technical: "Covers dutch traces, V_old correction, and true-online forward-view equivalence." },
  { chapter: 12, sourceTitle: "Sarsa(lambda)", bookAnchor: "Section 12.7 boxed algorithm", sourceCue: "Action-value traces", catalogIds: ["ch12-4"], easy: "Use traces for action values so recent state-action pairs share credit.", technical: "Covers accumulating/replacing action traces, linear action-value features, and epsilon-greedy control." },
  { chapter: 12, sourceTitle: "Watkins Q(lambda)", bookAnchor: "Section 12.8", sourceCue: "Off-policy trace cutting", catalogIds: ["ch12-5"], easy: "Use Q-learning targets but cut traces when exploratory actions break greediness.", technical: "Covers off-policy trace clearing, max-target backups, and eligibility management." },
  { chapter: 12, sourceTitle: "Tree Backup(lambda)", bookAnchor: "Section 12.8", sourceCue: "Expected trace backup", catalogIds: ["ch12-6"], easy: "Use expected branches instead of cutting traces on non-greedy actions.", technical: "Covers lambda version of tree-backup expectations and target-policy probabilities." },
  { chapter: 12, sourceTitle: "True online Sarsa(lambda)", bookAnchor: "Section 12.7 boxed algorithm", sourceCue: "True-online action-value control", catalogIds: ["ch12-10"], easy: "Bring dutch-trace correction to Sarsa control.", technical: "Covers Q_old, dutch traces for state-action features, and true-online control updates." },
  { chapter: 12, sourceTitle: "Expected Sarsa(lambda)", bookAnchor: "Section 12.9", sourceCue: "Expected action-value trace method", catalogIds: ["ch12-11"], easy: "Use expected next values with traces to reduce sampling noise.", technical: "Covers policy expectation in the TD error plus trace-based action-value updates." },
  { chapter: 12, sourceTitle: "GTD(lambda) / GQ(lambda)", bookAnchor: "Section 12.11", sourceCue: "Gradient trace algorithms", catalogIds: ["ch12-7"], easy: "Use gradient-TD corrections with traces for off-policy approximation.", technical: "Covers secondary weights, gradient objectives, and trace-extended off-policy prediction/control." },
  { chapter: 12, sourceTitle: "HTD(lambda)", bookAnchor: "Section 12.11", sourceCue: "Hybrid TD trace method", catalogIds: ["ch12-12"], easy: "Blend TD and gradient corrections for off-policy trace learning.", technical: "Covers hybrid correction goals and the practical stability-speed compromise." },
  { chapter: 12, sourceTitle: "Emphatic TD(lambda)", bookAnchor: "Section 12.11", sourceCue: "Emphatic traces", catalogIds: ["ch12-8"], easy: "Use follow-on emphasis through time so off-policy traced updates weight states correctly.", technical: "Covers emphasis recursion, interest, follow-on traces, and lambda extensions of emphatic TD." },

  { chapter: 13, sourceTitle: "Softmax policy parameterization", bookAnchor: "Section 13.1", sourceCue: "Discrete stochastic policy", catalogIds: ["ch13-1"], easy: "Turn preferences into probabilities.", technical: "Covers differentiable softmax policies, log-probability gradients, and preference scaling." },
  { chapter: 13, sourceTitle: "REINFORCE", bookAnchor: "Section 13.3 boxed algorithm", sourceCue: "Monte Carlo policy-gradient control", catalogIds: ["ch13-2"], easy: "Increase the probability of actions that led to high returns.", technical: "Covers return-weighted score-function gradients, gamma^t factor, and episodic Monte Carlo variance." },
  { chapter: 13, sourceTitle: "REINFORCE with baseline", bookAnchor: "Section 13.4 boxed algorithm", sourceCue: "Learned value baseline", catalogIds: ["ch13-3"], easy: "Judge an action by return above a learned state baseline.", technical: "Covers baseline invariance, advantage estimate G-vhat, separate theta/w step-sizes, and variance reduction." },
  { chapter: 13, sourceTitle: "One-step actor-critic", bookAnchor: "Section 13.5 boxed algorithm", sourceCue: "Online policy-gradient control", catalogIds: ["ch13-7"], easy: "Use a critic's TD error as the actor's immediate learning signal.", technical: "Covers semi-gradient critic, actor log-policy update, and bootstrapped advantage." },
  { chapter: 13, sourceTitle: "Actor-critic with eligibility traces", bookAnchor: "Section 13.5 boxed algorithm", sourceCue: "Actor and critic trace vectors", catalogIds: ["ch13-8"], easy: "Let TD errors credit several recent actor and critic features.", technical: "Covers separate actor/critic traces, lambda parameters, and TD-error-scaled parameter updates." },
  { chapter: 13, sourceTitle: "Continuing actor-critic", bookAnchor: "Section 13.6 boxed algorithm", sourceCue: "Average-reward actor-critic", catalogIds: ["ch13-5"], easy: "Use average-adjusted TD errors for never-ending tasks.", technical: "Covers differential TD error, R_bar update, continuing traces, and average-reward objective." },
  { chapter: 13, sourceTitle: "Gaussian policy gradients", bookAnchor: "Section 13.7", sourceCue: "Continuous-action policy", catalogIds: ["ch13-6"], easy: "For continuous actions, learn the mean and/or spread of a Gaussian action distribution.", technical: "Covers Gaussian log-probability gradients and continuous-control parameterization choices." },

  { chapter: 14, sourceTitle: "Rescorla-Wagner rule", bookAnchor: "Section 14.2", sourceCue: "Associative prediction error", catalogIds: ["ch14-1"], easy: "Change associative strength by surprise.", technical: "Covers error-driven associative learning, blocking interpretation, and links to constant-step prediction updates." },
  { chapter: 14, sourceTitle: "TD model of classical conditioning", bookAnchor: "Sections 14.3-14.4", sourceCue: "Prediction-error timing", catalogIds: ["ch14-2"], easy: "TD error moves backward from reward to predictors.", technical: "Covers temporal credit assignment in conditioning, higher-order predictions, and dopamine-like error timing." },
  { chapter: 14, sourceTitle: "Model-based goal-directed evaluation", bookAnchor: "Sections 14.5-14.6", sourceCue: "Model-free/model-based distinction", catalogIds: ["ch14-3"], easy: "Use an internal model to evaluate outcomes before acting.", technical: "Covers devaluation, contingency degradation, and planning-like evaluation in behavior." },

  { chapter: 15, sourceTitle: "Dopamine TD-error model", bookAnchor: "Sections 15.2-15.6", sourceCue: "Reward prediction error", catalogIds: ["ch15-1"], easy: "Dopamine bursts resemble a TD error signal moving to earlier predictors.", technical: "Covers phasic dopamine as delta_t, reward omission dips, and mapping to prediction-learning equations." },
  { chapter: 15, sourceTitle: "Neural actor-critic learning rule", bookAnchor: "Sections 15.7-15.8", sourceCue: "Actor and critic learning rules", catalogIds: ["ch15-2"], easy: "Separate neural circuits can learn values and action tendencies from the same TD error.", technical: "Covers actor-unit eligibility traces, critic value traces, and modulatory reinforcement signals." },

  { chapter: 16, sourceTitle: "TD-Gammon", bookAnchor: "Section 16.1", sourceCue: "Backgammon TD(lambda) with neural net", catalogIds: ["ch16-1"], easy: "Self-play plus TD learning trained a strong backgammon evaluator.", technical: "Covers nonlinear value approximation, self-play distribution, TD(lambda), and search/evaluation coupling." },
  { chapter: 16, sourceTitle: "Samuel checkers learning/search", bookAnchor: "Section 16.2", sourceCue: "Historical game-learning system", catalogIds: ["ch16-2"], easy: "Combine learned board evaluation with lookahead search.", technical: "Covers rote learning, feature-weighted evaluation, and search-backed policy improvement." },
  { chapter: 16, sourceTitle: "Watson wagering policy", bookAnchor: "Section 16.3", sourceCue: "Daily Double decision", catalogIds: ["ch16-3"], easy: "Choose a wager by maximizing expected match value.", technical: "Covers application-specific state, action, and value optimization under uncertainty." },
  { chapter: 16, sourceTitle: "RL memory controller", bookAnchor: "Section 16.4", sourceCue: "Memory access control", catalogIds: ["ch16-4"], easy: "Use RL to decide what to store, retrieve, or ignore.", technical: "Covers controller actions over memory operations and long-horizon credit assignment." },
  { chapter: 16, sourceTitle: "DQN Atari learning", bookAnchor: "Section 16.5", sourceCue: "Deep Q-network case study", catalogIds: ["ch16-5", "ch16-10", "ch16-11"], easy: "Use a neural Q-function, replay, and target network to learn Atari from pixels.", technical: "Covers Q-learning with convolutional approximation, experience replay, target networks, and stability modifications." },
  { chapter: 16, sourceTitle: "AlphaGo and AlphaGo Zero", bookAnchor: "Section 16.5", sourceCue: "Search plus self-play", catalogIds: ["ch16-6", "ch16-7"], easy: "Combine policy/value learning with tree search, then improve from self-play.", technical: "Covers policy/value networks, MCTS, expert pretraining versus tabula-rasa self-play, and search-improvement loops." },
  { chapter: 16, sourceTitle: "Web-service contextual bandit and LTV optimization", bookAnchor: "Section 16.6", sourceCue: "Recommendation/personalization applications", catalogIds: ["ch16-8", "ch16-12"], easy: "Use bandits or batch RL to choose offers or recommendations.", technical: "Covers contextual bandit optimization, fitted Q-iteration, logged-data constraints, and long-term value objectives." },
  { chapter: 16, sourceTitle: "Thermal soaring RL", bookAnchor: "Section 16.7", sourceCue: "Robotics/control application", catalogIds: ["ch16-9"], easy: "Learn how to exploit rising air to keep a glider aloft.", technical: "Covers sensor-derived states, continuous control considerations, and one-step Sarsa-style learning in a real control setting." },

  { chapter: 17, sourceTitle: "General value functions", bookAnchor: "Section 17.2", sourceCue: "Predictions beyond reward", catalogIds: ["ch17-1"], easy: "Predict many future signals, not only reward.", technical: "Covers cumulants, policies, discounts, and GVFs as reusable predictive knowledge." },
  { chapter: 17, sourceTitle: "Options framework", bookAnchor: "Section 17.3", sourceCue: "Temporally extended actions", catalogIds: ["ch17-2"], easy: "Treat a skill as an action with its own start rule, policy, and stop rule.", technical: "Covers initiation sets, intra-option policies, termination functions, and SMDP interpretation." },
  { chapter: 17, sourceTitle: "Intra-option learning", bookAnchor: "Section 17.3", sourceCue: "Learning during option execution", catalogIds: ["ch17-4"], easy: "Update option values from every compatible primitive transition.", technical: "Covers option continuation/termination backups and off-policy reuse across options." },
  { chapter: 17, sourceTitle: "Option value iteration", bookAnchor: "Section 17.3", sourceCue: "Bellman equations for options", catalogIds: ["ch17-5"], easy: "Plan over skills that last multiple steps.", technical: "Covers SMDP option backups, duration-dependent discounting, and policy improvement over options." },
  { chapter: 17, sourceTitle: "Reward design and shaping", bookAnchor: "Section 17.4", sourceCue: "Problem objective interface", catalogIds: ["ch17-3", "ch17-6"], easy: "Design rewards and shaping hints without creating loopholes.", technical: "Covers reward specification, validation loops, and potential-based shaping as a policy-invariant special case." },
];

export function sourceAuditsForChapter(chapter: number) {
  return algorithmSourceAudits.filter((entry) => entry.chapter === chapter);
}
