export interface ZeroKnowledgeRung {
  title: string;
  plain: string;
  visual: string;
  technical: string;
  practice: string;
  tags: string[];
}

export interface ZeroKnowledgeLadder {
  chapter: number;
  title: string;
  promise: string;
  rungs: ZeroKnowledgeRung[];
}

export const zeroKnowledgeModes = ["plain", "visual", "technical", "practice"] as const;

export const zeroKnowledgeLadders = [
  {
    chapter: 1,
    title: "What reinforcement learning is before symbols",
    promise: "Start with a learner, a world, feedback, and repeated choices before naming the mathematics.",
    rungs: [
      {
        title: "Agent and environment",
        plain: "Imagine a player inside a game: the player chooses moves, the game answers, and the player slowly changes how it plays.",
        visual: "Draw a circle for the agent, a box for the environment, an arrow for action going out, and arrows for state and reward coming back.",
        technical: "The agent-environment interface is a time-indexed interaction loop: at each step the agent observes information, selects an action, receives scalar reward, and transitions to a new situation.",
        practice: "Point to a real activity, such as cooking or a maze, and label the agent, environment, action, observation, and reward.",
        tags: ["agent", "environment", "action", "reward"],
      },
      {
        title: "Reward is the goal signal",
        plain: "Reward is not a teacher explaining the right answer; it is a score saying whether the recent outcome helped the goal.",
        visual: "Put reward as a small meter next to the environment arrow, then ask whether a good-looking move now might lower the meter later.",
        technical: "The reward signal defines the objective that the return aggregates, so changing reward changes the problem even if the state and action spaces remain the same.",
        practice: "Invent two possible rewards for the same robot and explain how each reward would train a different behavior.",
        tags: ["reward", "objective", "return"],
      },
      {
        title: "Value is learned prediction",
        plain: "A value is a forecast: if I am here and keep acting this way, how good will the future probably be?",
        visual: "Write a number above each board position and let bright numbers mean promising futures, not just good immediate moves.",
        technical: "A value function estimates expected return under a policy; it compresses many possible future reward sequences into a scalar prediction.",
        practice: "Choose two states in a toy game and say which should have higher value before any formula appears.",
        tags: ["value", "prediction", "policy"],
      },
      {
        title: "Learning is error correction",
        plain: "The learner guesses, sees what happens, compares the outcome with the guess, and nudges the guess.",
        visual: "Draw guess → outcome → difference → new guess as a small feedback wheel.",
        technical: "Most later updates share the pattern estimate plus step-size times target error; chapters differ mainly in how the target is constructed.",
        practice: "Say what the target and error would be in a one-step toy reward example.",
        tags: ["update", "error", "step-size"],
      },
      {
        title: "RL is not supervised labeling",
        plain: "The learner is not handed the correct action on every step; it must discover useful behavior by trying actions.",
        visual: "Compare a labeled flashcard with a maze: the maze gives consequences, not answer keys.",
        technical: "RL combines delayed credit assignment, exploration, and policy improvement, so data distribution depends on the learner's own behavior.",
        practice: "Explain why a bad early action can still teach something useful in reinforcement learning.",
        tags: ["exploration", "credit", "interaction"],
      },
    ],
  },
  {
    chapter: 2,
    title: "Bandits as the first learning laboratory",
    promise: "Remove state changes so exploration, estimates, and action choice can be studied cleanly.",
    rungs: [
      {
        title: "One situation, many arms",
        plain: "A bandit problem is like standing in front of several levers and learning which lever tends to pay best.",
        visual: "Draw one state dot connected to several action levers, each with a hidden reward cloud.",
        technical: "The contextual dynamics are collapsed away; the learner estimates action values from reward samples and chooses actions under uncertainty.",
        practice: "Name the action, reward sample, and action-value estimate in a restaurant-choice example.",
        tags: ["bandit", "action value", "sample"],
      },
      {
        title: "Sample averages are memory with shrinking trust",
        plain: "Early rewards move the estimate a lot; later rewards move it less because many samples are already stored.",
        visual: "Show a dot estimate being pulled toward each new reward with a shorter and shorter elastic string.",
        technical: "The incremental sample-average update uses step-size 1/n, producing the exact arithmetic mean in stationary reward distributions.",
        practice: "Update an estimate of 4 after seeing reward 10 as the fifth sample.",
        tags: ["sample average", "step-size", "stationary"],
      },
      {
        title: "Exploration protects against early luck",
        plain: "If you always choose the first lever that looks good, you may never discover the truly best one.",
        visual: "Color the current favorite bright, then leave a small flashlight sweeping across the other arms.",
        technical: "Epsilon-greedy action selection mixes exploitation of the current argmax estimate with random exploration of all actions.",
        practice: "Explain what epsilon controls and what happens when it is zero.",
        tags: ["epsilon", "exploration", "greedy"],
      },
      {
        title: "Uncertainty can be directed",
        plain: "Instead of exploring randomly, the learner can deliberately try actions it knows less about.",
        visual: "Draw each action with a height for estimated value and a halo for uncertainty bonus.",
        technical: "Upper-confidence-bound methods add a count-dependent optimism term, while gradient bandits learn preferences that define a stochastic policy.",
        practice: "Say why an action with a mediocre estimate but tiny count can be chosen by UCB.",
        tags: ["UCB", "preference", "softmax"],
      },
      {
        title: "Drift changes the right memory",
        plain: "If the levers change over time, ancient rewards should not control today's estimate forever.",
        visual: "Show old samples fading while recent samples stay darker on a timeline.",
        technical: "A constant step-size update gives exponentially decaying weight to old rewards, trading unbiased stationary estimates for nonstationary tracking.",
        practice: "Choose between 1/n and constant alpha for a recommendation system whose users change taste.",
        tags: ["nonstationary", "constant alpha", "tracking"],
      },
    ],
  },
  {
    chapter: 3,
    title: "The Markov decision process language",
    promise: "Turn interaction into the formal objects that every later algorithm manipulates.",
    rungs: [
      {
        title: "State is the information you condition on",
        plain: "A state is the learner's description of where it is and what matters for choosing next.",
        visual: "Draw the same physical room twice: once with enough labels to decide, once with missing labels that cause confusion.",
        technical: "In a Markov decision process, the state should make the conditional distribution of next state and reward depend only on current state and action.",
        practice: "Name one missing variable that would break the Markov property in a driving task.",
        tags: ["state", "Markov", "dynamics"],
      },
      {
        title: "Return collects delayed consequences",
        plain: "The return is the scorecard from now onward, not just the reward on the next step.",
        visual: "Draw future rewards as beads on a string, with farther beads shrinking under discounting.",
        technical: "Discounted return sums future rewards with powers of gamma, letting finite predictions represent long-run consequences.",
        practice: "Explain why a small immediate reward can be worse than a delayed larger reward.",
        tags: ["return", "discount", "future"],
      },
      {
        title: "Policy turns states into behavior",
        plain: "A policy is the learner's habit: in this situation, which actions does it tend to take?",
        visual: "Draw one state with arrows to actions; arrow thickness is action probability.",
        technical: "A policy can be deterministic or stochastic and induces value functions by controlling the distribution of future trajectories.",
        practice: "Describe how the value of a state changes when the policy becomes more cautious.",
        tags: ["policy", "probability", "trajectory"],
      },
      {
        title: "Bellman equations are one-step accounting",
        plain: "Value today equals expected reward now plus value of where you land next.",
        visual: "Put a value number on the current state, branch to possible next states, and average reward-plus-next-value along the branches.",
        technical: "Bellman expectation equations express value as a fixed point under policy averaging over actions and environment dynamics.",
        practice: "Say what is averaged over by the policy and what is averaged over by the model.",
        tags: ["Bellman", "expectation", "model"],
      },
      {
        title: "Optimality replaces averaging with choice",
        plain: "For the best possible behavior, the learner does not average over its old habit; it picks the best action.",
        visual: "Replace many policy arrows with a max gate that keeps the largest action branch.",
        technical: "Bellman optimality equations use maximization over actions to define v-star and q-star, the targets of optimal control methods.",
        practice: "Explain why evaluating a fixed policy and finding an optimal policy are different tasks.",
        tags: ["optimality", "max", "control"],
      },
    ],
  },
  {
    chapter: 4,
    title: "Dynamic programming with a known model",
    promise: "Use full model knowledge to see the clean backup machinery before sampling noise arrives.",
    rungs: [
      {
        title: "A model lets you rehearse all outcomes",
        plain: "If you know the rules of the world, you can update values by looking ahead without waiting for experience.",
        visual: "Draw a current state branching into every next state with probabilities written on the branches.",
        technical: "Dynamic programming assumes access to transition and reward dynamics, enabling expected backups over the full one-step distribution.",
        practice: "Say why chess rules are a model but a black-box robot environment may not be.",
        tags: ["model", "expected backup", "transition"],
      },
      {
        title: "Policy evaluation predicts a fixed habit",
        plain: "First hold the behavior still, then repeatedly refresh the value estimates for that behavior.",
        visual: "Freeze the policy arrows, then sweep a paint roller over all state values again and again.",
        technical: "Iterative policy evaluation applies Bellman expectation backups until the value table approaches the fixed point for the policy.",
        practice: "Explain why changing the policy during evaluation would change the target.",
        tags: ["policy evaluation", "sweep", "fixed point"],
      },
      {
        title: "Policy improvement acts on predictions",
        plain: "After the values say which actions look better, make the policy greedier with respect to those predictions.",
        visual: "Turn value labels into thicker arrows toward higher-valued successor states.",
        technical: "The policy improvement theorem justifies replacing a policy with actions whose q-values are no worse under the old policy.",
        practice: "Describe one reason inaccurate values can lead to premature greedy choices.",
        tags: ["improvement", "greedy", "q value"],
      },
      {
        title: "Generalized policy iteration is the loop",
        plain: "Evaluate behavior, improve behavior, evaluate again, and keep rotating until both settle.",
        visual: "Draw two gears: one labeled evaluation and one labeled improvement, each turning the other.",
        technical: "GPI captures the interacting processes of policy evaluation and policy improvement that reappear in model-free control.",
        practice: "Point to the evaluation and improvement parts of value iteration.",
        tags: ["GPI", "evaluation", "improvement"],
      },
      {
        title: "Value iteration truncates evaluation",
        plain: "You do not always need to fully evaluate each policy before improving; you can improve inside the backup.",
        visual: "Put a max gate directly inside the one-step backup box.",
        technical: "Value iteration applies Bellman optimality backups, combining truncated evaluation and greedy improvement toward the optimal fixed point.",
        practice: "Explain why value iteration still needs a model even though it skips explicit policy evaluation.",
        tags: ["value iteration", "optimality", "backup"],
      },
    ],
  },
  {
    chapter: 5,
    title: "Monte Carlo learning from completed episodes",
    promise: "Learn values from sampled returns when the model is unknown but episodes eventually finish.",
    rungs: [
      {
        title: "Episodes give complete scorecards",
        plain: "Monte Carlo methods wait until the story ends, then use the actual total future reward as the teaching signal.",
        visual: "Draw an episode as a path ending at a terminal flag, then send the final return back to earlier states.",
        technical: "MC prediction estimates value functions from sampled returns without bootstrapping from current value estimates.",
        practice: "Name a task where waiting for the episode end is natural and one where it is inconvenient.",
        tags: ["episode", "return", "Monte Carlo"],
      },
      {
        title: "First visit and every visit count samples differently",
        plain: "You can update a state once per episode or every time it appears; both are ways to average sampled returns.",
        visual: "Mark repeated visits to the same state on a trajectory and circle either the first mark or all marks.",
        technical: "First-visit and every-visit MC define different sample sets but both converge under suitable conditions in episodic prediction.",
        practice: "Explain what gets counted if a state appears three times in one episode.",
        tags: ["first visit", "every visit", "sample set"],
      },
      {
        title: "Control needs enough exploration",
        plain: "To learn which action is best, the learner must try actions often enough instead of only repeating current favorites.",
        visual: "Draw a value table for state-action pairs with some blank cells that exploration must fill.",
        technical: "MC control estimates action values and improves policies, often using exploring starts or epsilon-soft policies to maintain coverage.",
        practice: "Say why estimating only state values is not enough for model-free greedy control.",
        tags: ["control", "action value", "epsilon-soft"],
      },
      {
        title: "Off-policy learning reuses another policy's data",
        plain: "Sometimes you observe behavior from one policy but want to evaluate a different target policy.",
        visual: "Draw two colored paths through the same states: behavior generated the data, target is the policy being judged.",
        technical: "Importance sampling ratios correct expectations from a behavior policy to a target policy by reweighting sampled action probabilities.",
        practice: "Explain why a trajectory impossible under the target policy can receive zero weight.",
        tags: ["off-policy", "importance sampling", "behavior policy"],
      },
      {
        title: "Variance is the price of long sampled futures",
        plain: "Whole returns can be unbiased but wildly noisy, especially when many random future events are multiplied together.",
        visual: "Show many episode returns as tall scattered bars around a mean line.",
        technical: "Ordinary and weighted importance sampling expose a bias-variance tradeoff that motivates later bootstrapped and multi-step methods.",
        practice: "Describe why a long product of probability ratios can explode.",
        tags: ["variance", "weighted IS", "bias"],
      },
    ],
  },
  {
    chapter: 6,
    title: "Temporal-difference learning before the episode ends",
    promise: "Blend sampled reward with existing predictions so learning can happen step by step.",
    rungs: [
      {
        title: "TD error is one-step surprise",
        plain: "After one transition, ask whether reward plus the next prediction was better or worse than the old prediction.",
        visual: "Draw old value on the left, reward plus next value on the right, and the gap as the surprise arrow.",
        technical: "The TD error delta equals reward plus discounted next-state estimate minus current estimate and acts as a bootstrapped learning signal.",
        practice: "Compute whether delta is positive when reward is 1, next value is 5, discount is 0.9, and old value is 4.",
        tags: ["TD error", "bootstrapping", "prediction"],
      },
      {
        title: "TD learns online",
        plain: "The learner can update immediately after each step instead of waiting for the episode's final return.",
        visual: "Place small update sparks along a trajectory rather than one big spark at the terminal state.",
        technical: "TD(0) prediction uses a one-step bootstrapped target, combining sampling like MC with recursive value estimates like DP.",
        practice: "Explain why TD can be useful in continuing tasks.",
        tags: ["TD(0)", "online", "continuing"],
      },
      {
        title: "Sarsa learns the value of its own behavior",
        plain: "Sarsa updates using the action the current policy actually chooses next.",
        visual: "Trace S, A, R, S prime, A prime as five beads used by the update.",
        technical: "Sarsa is on-policy TD control because its target includes Q of the next action sampled from the behavior policy.",
        practice: "Say why epsilon-greedy exploration affects what Sarsa learns.",
        tags: ["Sarsa", "on-policy", "control"],
      },
      {
        title: "Q-learning learns a greedy target off-policy",
        plain: "Q-learning behaves however it needs to explore, but updates toward the best next action according to the current table.",
        visual: "At the next state, draw many action arrows and pass only the largest Q through a max gate.",
        technical: "The Q-learning target uses max over next-action values, making the update off-policy with respect to the greedy target policy.",
        practice: "Explain the difference between the action taken next and the action used in the Q-learning target.",
        tags: ["Q-learning", "off-policy", "max"],
      },
      {
        title: "Expected Sarsa averages next actions",
        plain: "Instead of sampling one next action or taking the max, Expected Sarsa averages over the policy's possible next actions.",
        visual: "Replace one next-action bead with a weighted fan of beads.",
        technical: "Expected Sarsa forms an expectation over the target policy's next-action distribution, often reducing variance relative to sampled Sarsa.",
        practice: "Say what probabilities are needed to compute the expected target.",
        tags: ["Expected Sarsa", "expectation", "variance"],
      },
    ],
  },
  {
    chapter: 7,
    title: "Multi-step backups as a spectrum",
    promise: "Connect one-step TD and full-return Monte Carlo by choosing how far a target looks ahead.",
    rungs: [
      {
        title: "Backup length is a bias-variance knob",
        plain: "A short backup learns quickly from estimates; a long backup listens more to actual sampled rewards.",
        visual: "Draw targets with windows of length 1, 2, 4, and episode end along the same trajectory.",
        technical: "n-step returns sum sampled rewards for n steps and bootstrap from the value estimate at the endpoint.",
        practice: "Explain what happens when n is one and when n reaches the episode end.",
        tags: ["n-step", "bias", "variance"],
      },
      {
        title: "Delayed updates need bookkeeping",
        plain: "If the target uses rewards several steps ahead, the learner must wait until those rewards arrive before updating an earlier state.",
        visual: "Draw a queue of recent states waiting for their n-step target to fill in.",
        technical: "Online n-step algorithms maintain time indices and update state-action pairs once the required future rewards and bootstrap estimate are available.",
        practice: "Say which time step can be updated after observing reward at time t+n.",
        tags: ["bookkeeping", "time index", "target"],
      },
      {
        title: "Off-policy multi-step ratios compound",
        plain: "Correcting several future actions requires multiplying several policy-probability ratios.",
        visual: "Place a small ratio weight on each future action and multiply them along the backup window.",
        technical: "n-step off-policy methods use products of target-over-behavior action probabilities, which can introduce high variance.",
        practice: "Explain why a single impossible target action can zero out a multi-step correction.",
        tags: ["off-policy", "ratio", "variance"],
      },
      {
        title: "Tree backup avoids sampling some actions",
        plain: "Instead of following only the sampled action path, a backup can average over action branches using expected values.",
        visual: "Draw a tree where sampled branches are bold but unsampled branches still contribute weighted leaves.",
        technical: "Tree-backup and related methods blend sampled transitions with policy expectations over action choices to reduce reliance on importance sampling.",
        practice: "Point out which parts of the tree use sampled rewards and which use policy probabilities.",
        tags: ["tree backup", "expectation", "sampling"],
      },
      {
        title: "The chapter teaches target design",
        plain: "You are not memorizing one algorithm; you are learning how to choose a target between TD and Monte Carlo.",
        visual: "Put TD(0) on one end of a slider, full MC on the other, and n-step targets in between.",
        technical: "Multi-step methods expose a continuum of bootstrapping depth, variance, delay, and off-policy correction choices.",
        practice: "Choose a shorter or longer backup for a noisy long-horizon task and defend the choice.",
        tags: ["target design", "backup", "continuum"],
      },
    ],
  },
  {
    chapter: 8,
    title: "Planning and learning with models",
    promise: "Use a model to turn experience into rehearsal, search, and prioritized updates.",
    rungs: [
      {
        title: "A model predicts experience",
        plain: "A model is the learner's sketch of what would happen after an action, even before taking that action again.",
        visual: "Draw a small simulator box that accepts state and action, then emits predicted reward and next state.",
        technical: "A model maps state-action pairs to predicted transitions and rewards, enabling simulated experience for planning backups.",
        practice: "Give one example of a perfect model and one example of a learned approximate model.",
        tags: ["model", "simulation", "planning"],
      },
      {
        title: "Dyna interleaves acting and rehearsing",
        plain: "The agent learns from real steps, updates its model, then practices extra imagined steps.",
        visual: "Draw a triangle: real experience, value update, model update, simulated update.",
        technical: "Dyna architectures combine direct RL updates with planning updates generated from a learned model of experienced transitions.",
        practice: "Explain why Dyna can improve faster than direct learning when the model is useful.",
        tags: ["Dyna", "planning update", "direct RL"],
      },
      {
        title: "Priority focuses computation",
        plain: "If a value changes a lot, update the states that depend on it before wasting effort elsewhere.",
        visual: "Put surprising states into a priority queue with the largest surprise at the front.",
        technical: "Prioritized sweeping backs up predecessors whose estimated values are most likely affected by recent changes.",
        practice: "Say why a tiny TD error might not deserve immediate planning computation.",
        tags: ["priority", "predecessor", "sweeping"],
      },
      {
        title: "Sampling can beat exhaustive sweeps",
        plain: "In huge worlds, planning every state is impossible, so useful sampled trajectories may be better.",
        visual: "Compare a full grid sweep with a few bright paths through likely states.",
        technical: "Trajectory sampling concentrates backups on states visited under relevant policies, trading complete coverage for focused computation.",
        practice: "Explain why exhaustive dynamic programming becomes wasteful in large sparse tasks.",
        tags: ["trajectory sampling", "large state space", "focus"],
      },
      {
        title: "Search is planning at decision time",
        plain: "Sometimes the agent plans right before acting by looking ahead from the current state.",
        visual: "Draw a search tree rooted at now, expanding possible futures before one action is chosen.",
        technical: "Heuristic search and Monte Carlo tree search use model-based rollouts or backups to estimate action values for the current decision.",
        practice: "Name one reason decision-time planning can be expensive but powerful.",
        tags: ["search", "MCTS", "decision time"],
      },
    ],
  },
  {
    chapter: 9,
    title: "Function approximation as generalization",
    promise: "Replace tables with features and weights so learning can scale beyond small discrete worlds.",
    rungs: [
      {
        title: "Tables do not scale",
        plain: "A table needs one slot for every state, but real problems can have too many states or continuous observations.",
        visual: "Draw a table exploding into millions of cells, then compress it into a feature vector.",
        technical: "Function approximation represents value estimates through parameters shared across many states, enabling generalization.",
        practice: "Explain why a table is impossible for raw camera images.",
        tags: ["function approximation", "generalization", "features"],
      },
      {
        title: "Features describe what matters",
        plain: "Features are the measurements the learner uses to recognize similar situations.",
        visual: "Turn a messy scene into a small list of numbers such as distance, speed, and danger.",
        technical: "A feature vector maps states to numeric inputs for a value function, often making nearby or related states share parameters.",
        practice: "Choose three features for a balancing robot and explain what each captures.",
        tags: ["feature vector", "representation", "state"],
      },
      {
        title: "Weights are shared memory",
        plain: "Changing one weight can change predictions for many states at once.",
        visual: "Draw one knob connected by wires to many state predictions.",
        technical: "In linear value approximation, the estimate is the dot product of weights and features, so updates propagate through active features.",
        practice: "Say why shared weights can help in one state and accidentally hurt another.",
        tags: ["weights", "linear", "dot product"],
      },
      {
        title: "Gradients point to parameter changes",
        plain: "A gradient says which way to turn the knobs to reduce a prediction error.",
        visual: "Draw a hill of error and an arrow pointing downhill in weight space.",
        technical: "Gradient Monte Carlo follows the negative gradient of squared return error, while semi-gradient TD treats the bootstrap target as fixed.",
        practice: "Explain why semi-gradient TD is not the same as taking a full gradient of the true objective.",
        tags: ["gradient", "semi-gradient", "error"],
      },
      {
        title: "Representation controls what can be learned",
        plain: "If the features cannot express the right pattern, no update rule can magically store it.",
        visual: "Show a shadow of a complex shape projected onto a simple line: information is lost.",
        technical: "Approximation introduces representational error, interference, and stability questions that do not arise in small exact tables.",
        practice: "Name one sign that poor features, not the learning rate, are limiting performance.",
        tags: ["representation", "interference", "stability"],
      },
    ],
  },
  {
    chapter: 10,
    title: "Control with approximation",
    promise: "Use approximate action values to improve behavior when tabular control is no longer possible.",
    rungs: [
      {
        title: "Action values need features too",
        plain: "When states and actions are too many for a table, the learner estimates q-values from descriptions.",
        visual: "Feed state and action descriptors into one value-estimate machine.",
        technical: "Approximate control represents q(s,a) with parameters, allowing generalization over state-action pairs.",
        practice: "Explain why action features may matter in a continuous-action robot.",
        tags: ["q approximation", "state-action", "control"],
      },
      {
        title: "Semi-gradient Sarsa updates behavior values",
        plain: "After acting, compare the q-value with a sampled target and nudge the weights for the chosen action.",
        visual: "Highlight the chosen action's feature vector while other action estimates remain indirectly affected through shared weights.",
        technical: "Episodic semi-gradient Sarsa uses a bootstrapped target and updates q-parameters by the gradient of the current estimate.",
        practice: "Identify the sampled action and next action in an approximate Sarsa update.",
        tags: ["Sarsa", "semi-gradient", "weights"],
      },
      {
        title: "Average reward handles continuing tasks",
        plain: "For tasks that never end, the goal can be long-run reward per time step rather than discounted episode return.",
        visual: "Replace terminal flags with an endless conveyor belt and a running reward-rate meter.",
        technical: "Average-reward formulations learn differential values relative to the estimated average reward baseline.",
        practice: "Name a continuing task where discounting feels less natural than average reward.",
        tags: ["average reward", "continuing", "differential"],
      },
      {
        title: "Control adds instability pressure",
        plain: "Changing behavior changes the data, and shared weights make each update affect many decisions.",
        visual: "Draw a moving target connected to a shared parameter board.",
        technical: "Approximate control couples bootstrapped targets, policy improvement, and representation, making stability more delicate than tabular prediction.",
        practice: "Explain why a policy change can alter the distribution of future training samples.",
        tags: ["stability", "policy improvement", "distribution"],
      },
      {
        title: "Mountain Car shows shaping through representation",
        plain: "A learner can solve a hard control task when features let it connect similar positions and velocities.",
        visual: "Tile the position-velocity plane and color tiles by action preference.",
        technical: "Coarse coding and tile coding provide sparse overlapping features that generalize value updates locally across continuous spaces.",
        practice: "Explain why overlapping tiles are more flexible than one giant coarse bin.",
        tags: ["tile coding", "Mountain Car", "generalization"],
      },
    ],
  },
  {
    chapter: 11,
    title: "The off-policy approximation danger zone",
    promise: "Understand why bootstrapping, off-policy data, and approximation can destabilize learning together.",
    rungs: [
      {
        title: "Off-policy means two roles for policy",
        plain: "One policy creates the data, while another policy is the one you want to evaluate or improve.",
        visual: "Draw a behavior road producing samples and a target road receiving the lesson.",
        technical: "The behavior policy determines the sampling distribution, while the target policy defines the values or objective being learned.",
        practice: "Give one reason off-policy learning is useful despite being harder.",
        tags: ["off-policy", "behavior", "target"],
      },
      {
        title: "The deadly triad is a warning label",
        plain: "Approximation, bootstrapping, and off-policy learning are each useful, but together they can make estimates blow up.",
        visual: "Draw a triangle with one danger word on each corner and instability in the center.",
        technical: "The deadly triad identifies the combination that can make TD-style updates diverge under function approximation.",
        practice: "Point to which corner is missing in ordinary tabular on-policy TD.",
        tags: ["deadly triad", "divergence", "bootstrapping"],
      },
      {
        title: "Distribution matters",
        plain: "The learner updates where data appears, not necessarily where the target policy most needs accuracy.",
        visual: "Shade sampled states dark and unsampled target-relevant states pale.",
        technical: "Projected Bellman objectives depend on the sampling distribution, creating a mismatch between approximation geometry and target-policy evaluation.",
        practice: "Explain why rare but important states can be poorly learned.",
        tags: ["sampling distribution", "projection", "objective"],
      },
      {
        title: "Gradient TD changes the objective",
        plain: "Some algorithms become stable by optimizing a carefully defined error instead of using the naive TD update.",
        visual: "Replace an unstable feedback loop with a measured objective gauge.",
        technical: "Gradient-TD methods introduce auxiliary weights to descend objectives related to projected Bellman error under off-policy sampling.",
        practice: "Say why adding an auxiliary vector can be worth the complexity.",
        tags: ["Gradient TD", "MSPBE", "auxiliary weights"],
      },
      {
        title: "Emphasis reweights credit",
        plain: "The learner can decide which states deserve stronger updates so the target prediction is supported by the data.",
        visual: "Draw update arrows with different thicknesses based on follow-on interest.",
        technical: "Emphatic methods adjust update weighting to account for target-policy visitation influence under off-policy training.",
        practice: "Explain how reweighting updates differs from changing the value formula itself.",
        tags: ["emphasis", "follow-on", "weighting"],
      },
    ],
  },
  {
    chapter: 12,
    title: "Eligibility traces as fading memory",
    promise: "Spread credit backward through recent features while preserving the backup-spectrum view.",
    rungs: [
      {
        title: "A trace remembers recent responsibility",
        plain: "Recent states or features leave footprints, so a later surprise can update them too.",
        visual: "Draw footprints behind the agent that fade as time passes.",
        technical: "An eligibility trace accumulates or replaces recent feature activations and decays by gamma lambda over time.",
        practice: "Explain why a feature active many steps ago gets less credit than one active now.",
        tags: ["eligibility trace", "credit", "decay"],
      },
      {
        title: "Lambda mixes backup lengths",
        plain: "Lambda lets the learner blend short and long backups instead of choosing one n.",
        visual: "Show a stack of n-step targets with weights that shrink geometrically.",
        technical: "The lambda-return is a weighted mixture of n-step returns, connecting TD(0) and Monte Carlo endpoints.",
        practice: "Say what happens conceptually as lambda moves toward one.",
        tags: ["lambda-return", "n-step", "mixture"],
      },
      {
        title: "Forward view and backward view meet",
        plain: "You can define learning by looking forward to mixed returns or implement it online by carrying traces backward.",
        visual: "Draw a forward telescope of future rewards and a backward trail of fading traces, then connect them.",
        technical: "Under appropriate conditions, backward-view TD(lambda) implements the forward-view lambda-return idea incrementally.",
        practice: "Explain why the backward view is useful for online learning.",
        tags: ["forward view", "backward view", "TD(lambda)"],
      },
      {
        title: "True online traces fix timing details",
        plain: "When approximation and online updates interact, small timing corrections can make the implemented update match the intended target better.",
        visual: "Show a trace line being corrected as the weight vector changes during the episode.",
        technical: "True online TD(lambda) and Dutch traces preserve a cleaner equivalence to the forward view with changing weights.",
        practice: "Say why changing weights during an episode complicates the simple trace story.",
        tags: ["true online", "Dutch trace", "equivalence"],
      },
      {
        title: "Traces apply to control too",
        plain: "The same fading-credit idea can update action values and policies, but off-policy corrections become delicate.",
        visual: "Attach fading footprints to state-action pairs instead of states alone.",
        technical: "Control methods such as Sarsa(lambda) use eligibility traces for action-value updates, while off-policy trace variants manage correction and stability.",
        practice: "Explain why traces can speed learning in a delayed-reward maze.",
        tags: ["Sarsa(lambda)", "control", "off-policy traces"],
      },
    ],
  },
  {
    chapter: 13,
    title: "Policy gradients as direct policy learning",
    promise: "Move from estimating values for greedy choice to directly adjusting a parameterized policy.",
    rungs: [
      {
        title: "The policy can be the main object",
        plain: "Instead of learning values first and choosing greedily, the learner can tune the action probabilities themselves.",
        visual: "Draw action-probability sliders controlled by a parameter knob.",
        technical: "A parameterized stochastic policy maps states to action distributions, and learning changes parameters to improve expected return.",
        practice: "Name one reason a stochastic policy may be useful even after learning.",
        tags: ["policy", "parameter", "stochastic"],
      },
      {
        title: "Gradients need a performance objective",
        plain: "To improve the policy, we need a hill to climb: a number saying how good the current policy is.",
        visual: "Draw policy parameters as a point on a landscape of expected return.",
        technical: "Policy-gradient methods estimate the gradient of an objective J(theta), often using sampled returns weighted by score functions.",
        practice: "Explain what it means to move parameters uphill.",
        tags: ["objective", "gradient", "J(theta)"],
      },
      {
        title: "The score function credits chosen actions",
        plain: "If an action was followed by good return, increase the log-probability direction that made it more likely.",
        visual: "Draw a chosen action arrow being thickened after a high-return episode.",
        technical: "REINFORCE uses the gradient of log policy probability times return as an unbiased policy-gradient sample.",
        practice: "Say why unchosen actions are affected indirectly through probability normalization.",
        tags: ["REINFORCE", "log probability", "return"],
      },
      {
        title: "Baselines reduce noise without changing direction",
        plain: "Subtracting a fair reference level tells the learner whether the outcome was better than expected, not just large.",
        visual: "Put a horizontal baseline on a reward chart and measure advantage above or below it.",
        technical: "Action-independent baselines can reduce variance while preserving the expected policy gradient; value functions often serve this role.",
        practice: "Explain why the baseline must not depend on which action was sampled.",
        tags: ["baseline", "advantage", "variance"],
      },
      {
        title: "Actor-critic splits doing and judging",
        plain: "The actor changes the policy; the critic estimates values that make the actor's updates less noisy.",
        visual: "Draw an actor choosing actions and a critic sending an advantage signal back.",
        technical: "Actor-critic methods combine policy-gradient updates with learned value estimates or TD errors as low-variance credit signals.",
        practice: "Identify the actor and critic in a system that has both policy parameters and value weights.",
        tags: ["actor-critic", "advantage", "TD error"],
      },
    ],
  },
  {
    chapter: 14,
    title: "Psychology through prediction and control",
    promise: "Use RL ideas to reinterpret conditioning, surprise, and learned behavior in animals and people.",
    rungs: [
      {
        title: "Conditioning is predictive learning",
        plain: "A cue becomes important when it predicts something that matters later.",
        visual: "Draw a bell cue arrow pointing to food, then a prediction number growing beside the cue.",
        technical: "Associative learning models update cue strengths in response to prediction errors between expected and observed outcomes.",
        practice: "Explain why a cue paired with food becomes valuable before food appears.",
        tags: ["conditioning", "cue", "prediction"],
      },
      {
        title: "Blocking reveals shared prediction error",
        plain: "If one cue already predicts the outcome, a new redundant cue may learn little.",
        visual: "Show total prediction nearly matching the outcome, leaving little surprise for the new cue.",
        technical: "Blocking occurs when existing associative strength explains the outcome, reducing prediction error available to train additional cues.",
        practice: "Describe blocking using the words prediction and surprise.",
        tags: ["blocking", "prediction error", "association"],
      },
      {
        title: "Timing requires temporal predictions",
        plain: "Animals learn not only what will happen but also when it is expected.",
        visual: "Place predictions along a timeline between cue and outcome.",
        technical: "Temporal-difference models extend error-driven learning across time, shifting prediction from reward arrival back to earlier cues.",
        practice: "Explain how TD learning differs from a one-time cue-strength update.",
        tags: ["timing", "TD", "cue"],
      },
      {
        title: "State representation shapes behavior",
        plain: "What the learner treats as the same or different situation changes what it can learn.",
        visual: "Draw two similar cues either merged into one state or split into separate states.",
        technical: "Stimulus representation and state construction determine generalization, discrimination, and which predictions can be assigned to which cues.",
        practice: "Give an example where two cues should be distinguished rather than generalized.",
        tags: ["representation", "generalization", "stimulus"],
      },
      {
        title: "Psychology adds constraints to algorithms",
        plain: "Behavioral data asks whether an RL mechanism explains real learning patterns, not just whether it solves a task.",
        visual: "Connect a lab behavior curve to an algorithmic prediction-error curve.",
        technical: "The chapter uses RL models as scientific explanations for behavioral phenomena while acknowledging biological and representational complexity.",
        practice: "Say why matching average reward is not enough to explain animal behavior.",
        tags: ["behavior", "model", "science"],
      },
    ],
  },
  {
    chapter: 15,
    title: "Neuroscience and reward prediction error",
    promise: "Connect TD-style surprise signals to dopamine timing without oversimplifying the brain.",
    rungs: [
      {
        title: "Dopamine is not just pleasure",
        plain: "A dopamine burst can signal that something was better than predicted, not merely that reward arrived.",
        visual: "Draw dopamine response moving from reward time to cue time after learning.",
        technical: "Phasic dopamine activity has been interpreted as resembling temporal-difference reward prediction error across learning stages.",
        practice: "Explain why the response can shift from reward to cue after training.",
        tags: ["dopamine", "prediction error", "cue"],
      },
      {
        title: "Omitted reward creates negative error",
        plain: "If a reward was expected and does not appear, the surprise goes below baseline.",
        visual: "Draw a dip at the time an expected reward is missing.",
        technical: "TD error becomes negative when predicted future value is not realized, matching qualitative patterns of suppressed phasic response.",
        practice: "Say what the value prediction was before the omitted reward.",
        tags: ["omission", "negative error", "value"],
      },
      {
        title: "Actor-critic is a useful analogy",
        plain: "One system may evaluate outcomes while another biases actions, but the brain is more complex than the diagram.",
        visual: "Draw critic-to-actor arrows, then add a note that biological circuits are not literal software modules.",
        technical: "Actor-critic architectures offer computational hypotheses for basal ganglia function and dopamine-modulated learning.",
        practice: "Identify what the critic estimates and what the actor changes in the analogy.",
        tags: ["actor-critic", "basal ganglia", "analogy"],
      },
      {
        title: "Prediction errors train many predictions",
        plain: "The same surprise idea can help learn about cues, timing, and action consequences.",
        visual: "Show one error signal branching to update several predictive maps.",
        technical: "TD-like mechanisms can support learned value predictions and action preferences, but details depend on circuit, timescale, and representation.",
        practice: "Explain why a single global error signal may need local eligibility information.",
        tags: ["eligibility", "circuit", "prediction"],
      },
      {
        title: "Neuroscience is evidence, not proof of one algorithm",
        plain: "The match to TD error is powerful, but it does not mean the brain runs one textbook update line by line.",
        visual: "Place the algorithm curve beside experimental data with a cautious bridge between them.",
        technical: "The chapter treats RL as a computational lens for interpreting neural data while preserving uncertainty about implementation and scope.",
        practice: "State one reason model fits should be interpreted carefully.",
        tags: ["evidence", "modeling", "limits"],
      },
    ],
  },
  {
    chapter: 16,
    title: "Applications as complete systems",
    promise: "Study how RL ingredients become working systems in games, robotics, and large-scale learning.",
    rungs: [
      {
        title: "Applications combine many pieces",
        plain: "A successful RL system is rarely just one update rule; it includes representation, data, exploration, search, and engineering choices.",
        visual: "Draw a system stack with environment, data pipeline, learner, evaluator, and deployment loop.",
        technical: "Case studies integrate value learning, policy improvement, function approximation, planning, and domain-specific design constraints.",
        practice: "Name three non-algorithm pieces needed to make an RL application work.",
        tags: ["system", "engineering", "pipeline"],
      },
      {
        title: "Self-play creates a curriculum",
        plain: "A game-playing agent can improve by playing against versions of itself that get stronger over time.",
        visual: "Draw policy versions as a ladder where each version generates harder games for the next.",
        technical: "Self-play turns the current policy into a data generator, often coupled with value learning and search for policy improvement.",
        practice: "Explain why self-play can produce training examples without human labels.",
        tags: ["self-play", "curriculum", "game"],
      },
      {
        title: "Search can amplify learned values",
        plain: "A value network can guide search, and search can produce better targets for the network.",
        visual: "Draw a loop from policy/value network to tree search to improved training targets and back.",
        technical: "Systems such as AlphaGo-style agents combine learned policy/value functions with search-based action selection and self-generated data.",
        practice: "Say why search at move time can be stronger than raw policy output.",
        tags: ["search", "AlphaGo", "value network"],
      },
      {
        title: "Robotics exposes sample and safety costs",
        plain: "A robot cannot try millions of dangerous random actions as cheaply as a simulation can.",
        visual: "Put a cost meter and safety boundary around the agent-environment loop.",
        technical: "Physical-control applications must account for sample efficiency, safety, exploration constraints, and transfer between model/simulation and reality.",
        practice: "Explain why model-based planning can be attractive in robotics.",
        tags: ["robotics", "sample efficiency", "safety"],
      },
      {
        title: "Applications teach design patterns",
        plain: "The point is not to copy a famous system, but to recognize how RL components are assembled for a domain.",
        visual: "Turn a case study into reusable blocks: representation, objective, data source, update, evaluation.",
        technical: "The chapter's examples show recurring architectural patterns rather than universal recipes; each task changes the constraints.",
        practice: "For a new application, list state, action, reward, data source, and evaluation metric before choosing an algorithm.",
        tags: ["design pattern", "case study", "evaluation"],
      },
    ],
  },
  {
    chapter: 17,
    title: "Frontiers: abstraction, questions, and goals",
    promise: "Finish by asking how agents should build states, choose rewards, compose skills, and predict more than reward.",
    rungs: [
      {
        title: "State is a design problem",
        plain: "The learner can only act intelligently with respect to information its state representation preserves.",
        visual: "Draw a camera image being compressed into task-relevant state variables, with some information intentionally ignored.",
        technical: "State construction determines Markov structure, generalization, and which value predictions or policies are learnable.",
        practice: "Name one variable that should be included and one that can be ignored in a delivery-robot state.",
        tags: ["state", "representation", "abstraction"],
      },
      {
        title: "Reward design is goal design",
        plain: "A badly chosen reward can make the agent optimize the wrong behavior perfectly.",
        visual: "Draw a reward sign pointing toward a shortcut that violates the designer's real intent.",
        technical: "Reward specification defines the optimization problem and raises issues of alignment, shaping, side effects, and evaluation.",
        practice: "Invent a reward that could be gamed by an agent and then repair it.",
        tags: ["reward design", "alignment", "shaping"],
      },
      {
        title: "Options are temporally extended actions",
        plain: "Instead of choosing only primitive moves, an agent can choose a reusable skill that runs for several steps.",
        visual: "Replace many small action arrows with one thick option arrow labeled by its stopping rule.",
        technical: "An option includes an initiation set, internal policy, and termination condition, enabling hierarchical control and temporal abstraction.",
        practice: "Define a hallway-navigation option with where it can start, what it does, and when it stops.",
        tags: ["options", "hierarchy", "termination"],
      },
      {
        title: "General value functions ask many predictive questions",
        plain: "An agent can predict signals besides reward, over horizons besides the task objective.",
        visual: "Draw many small question cards attached to one stream of experience: battery, contact, danger, progress.",
        technical: "GVFs define predictions through cumulants, policies, discounts, and state representation, turning value learning into a general predictive knowledge framework.",
        practice: "Create a GVF question for a robot sensor that is not directly reward.",
        tags: ["GVF", "cumulant", "prediction"],
      },
      {
        title: "The frontier is integration",
        plain: "Advanced RL asks how to combine learning, planning, abstraction, representation, and objectives into robust agents.",
        visual: "Draw the whole book as a map: interaction loop at the center, with branches to values, policies, models, traces, gradients, options, and GVFs.",
        technical: "The closing themes connect the book's methods to open problems in scalable intelligence, continual learning, hierarchical behavior, and objective specification.",
        practice: "Pick one open problem and trace which earlier chapters provide its building blocks.",
        tags: ["integration", "frontier", "continual learning"],
      },
    ],
  },
] satisfies ZeroKnowledgeLadder[];

export function zeroKnowledgeLadderForChapter(chapter: number) {
  const ladder = zeroKnowledgeLadders.find((entry) => entry.chapter === chapter);
  if (!ladder) throw new Error(`Missing zero-knowledge ladder for chapter ${chapter}`);
  return ladder;
}

export function zeroKnowledgeRungCount(chapter?: number) {
  const ladders = typeof chapter === "number" ? [zeroKnowledgeLadderForChapter(chapter)] : zeroKnowledgeLadders;
  return ladders.reduce((sum, ladder) => sum + ladder.rungs.length, 0);
}

export function zeroKnowledgeModeCount(chapter?: number) {
  return zeroKnowledgeRungCount(chapter) * zeroKnowledgeModes.length;
}
